language: python

matrix:
  include:
    - os: linux
      python: "2.7"
      env: TOXENV=py27
    - os: linux
      python: "3.4"
      env: TOXENV=py34
    - os: linux
      python: "3.5"
      env: TOXENV=py35
    - os: linux
      python: "3.6"
      env: TOXENV=py36
    - os: linux
      python: "3.7"
      env: TOXENV=py37
      dist: xenial
      sudo: true
    - os: linux
      python: "pypy"
      env: TOXENV=pypy
    - os: linux
      python: "pypy3"
      env: TOXENV=pypy3
    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=2.7
        - TOXENV=py27
    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=3.6
        - TOXENV=py36

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then chmod +x .travis/install.sh && .travis/install.sh; fi

install:
  - python -m pip install tox
  - tox --notest  # Note: keep it!

script:
  - tox

notifications:
    email: false
