# Beta opt-in
# https://docs.travis-ci.com/user/build-config-validation#beta-opt-in
version: ~> 1.0

language: python
dist: xenial
os: linux

env:
  global:
    - MAKEFLAGS="-j 2"

jobs:
  fast_finish: true
  include:
    - name: Python 2.7 on GNU/Linux
      os: linux
      python: "2.7"
      env: TOXENV=py27
    - name: Python 3.5 on GNU/Linux
      os: linux
      python: "3.5"
      env:
        - TOXENV=py35
        # To help catch regression seen in #615
        - LC_ALL=C

    - name: PyPy 2.7 on GNU/Linux
      os: linux
      python: "pypy"
      env: TOXENV=pypy

    - name: Python 2.7 on macOS
      os: osx
      language: shell
      install:
        - unset PYENV_ROOT
        - curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
        - export PATH="$HOME/.pyenv/bin:$PATH"
        - eval "$(pyenv init -)"
        - pyenv install --skip-existing 2.7.16
        - pyenv global 2.7.16
      env: TOXENV=py27
    - name: Python 3.5 on macOS
      os: osx
      language: shell
      install:
        - unset PYENV_ROOT
        - curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
        - export PATH="$HOME/.pyenv/bin:$PATH"
        - eval "$(pyenv init -)"
        - pyenv install --skip-existing 3.5.10
        - pyenv global 3.5.10
      env: TOXENV=py35

    - name: Python 2.7 on Windows
      os: windows
      language: shell
      before_install:
        - choco install python2
      env:
        - TOXENV=py27
        - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"
    - name: Python 3.5 on Windows
      os: windows
      language: shell
      before_install:
        - choco install python3 --version=3.5.4
      env:
        - TOXENV=py35
        - export PATH="/c/Python35:/c/Python35/Scripts:$PATH"

before_script:
  - python -m pip install -U pip tox
  - python -m tox --notest  # Note: keep it!

script:
  - python -m tox

notifications:
  email: false
