name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - ".github/workflows/tests.yml"
      - "requirements-tests.txt"
      - "setup.*"
      - "src/**/*"
      - "tests/*.py"
      - "docs/**/*"

jobs:
  tox:
    name: ${{ matrix.tox.name }} ${{ matrix.os.name }} ${{ matrix.python }}
    runs-on: ${{ matrix.os.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        tox:
          - name: mypy
            environment: mypy
          - name: Test
            environment: py
        python:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "pypy-3.8"
          - "pypy-3.9"
        os:
          - name: Linux
            runs-on: [ubuntu-latest]
          - name: macOS
            runs-on: [macos-latest]
          - name: Windows
            runs-on: [windows-latest]
        include:
          - tox:
              name: Flake8
              environment: flake8
            python: "3.11"
            os:
              name: Linux
              runs-on: [ubuntu-latest]
          - tox:
              name: Docs
              environment: docs
            python: "3.11"
            os:
              name: Linux
              runs-on: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install test dependencies
        run: |
          python -m pip install tox

      - name: Run ${{ matrix.tox.name }} in tox
        run: |
          python -m tox -e ${{ matrix.tox.environment }}
