name: Tests

on:
  push:
    branches:
      - master
  pull_request:

  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch, tag or SHA to release from'
        required: true
        default: 'master'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.event_name }}-${{ github.event_name != 'pull_request' && github.sha || '' }}
  cancel-in-progress: true

jobs:
  tox:
    name: ${{ matrix.tox.name }} ${{ matrix.os.emoji }} ${{ matrix.os.name }} ${{ matrix.python }}
    runs-on: ${{ matrix.os.runs-on }}
    timeout-minutes: ${{ matrix.tox.timeout }}
    strategy:
      fail-fast: false
      matrix:
        tox:
          - name: Types
            environment: types
            timeout: 15
          - name: Test
            environment: py
            timeout: 15
        os:
          - name: Linux
            matrix: linux
            emoji: 🐧
            runs-on: [ubuntu-latest]
          - name: macOS
            matrix: macos
            emoji: 🍎
            runs-on: [macos-latest]
          - name: Windows
            matrix: windows
            emoji: 🪟
            runs-on: [windows-latest]
        python:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13-dev"
          - "pypy-3.9"
        include:
          - tox:
              name: Linter
              environment: lint
              timeout: 5
            python: "3.11"
            os:
              name: Linux
              emoji: 🐧
              runs-on: [ubuntu-latest]
          - tox:
              name: Docs
              environment: docs
              timeout: 5
            python: "3.11"
            os:
              name: Linux
              emoji: 🐧
              runs-on: [ubuntu-latest]
        exclude:
          - os:
              matrix: macos
            python: "pypy-3.9"
          - os:
              matrix: windows
            python: "pypy-3.9"


    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: pip

      - name: Install test dependencies
        run: python -m pip install tox

      - name: Run ${{ matrix.tox.name }} in tox
        run: python -m tox -e ${{ matrix.tox.environment }}
