name: "Python package"

on: [push]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      max-parallel: 3
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        python-version: [2.7, 3.5, pypy2]
        exclude:
          # the pypy2 on Windows tests appear to hang, so let's disable it until we can figure out why
          - os: windows-latest
            python-version: pypy2
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{matrix.python-version}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-tests.txt
      - name: flake8
        run: python -m flake8 docs tools src tests
      - name: pytest
        run: python -bb -m pytest --showlocals -v --cov=watchdog --cov-report=term-missing